run_name: mcts_inference_valid
data_dir: datasets/minif2f.jsonl
split: valid
max_depth: 20

worker:
  num_procs: 163

context:
  num_procs: 0
  batch_size: 40

lean:
  num_procs: 12

completion:
  num_procs: 4
  batch_size: 100
  max_num_batched_tokens: 8192
  sampling:
    max_tokens: 512
    temperature: 0.0
    top_k: 1
    top_p: 1.0
    stop: ["--", "/--"] # stop before next step (proxy = comment)

policy_value:
  num_procs: 4
  type: fast
  batch_size: 40
  branching_factor: 1
  sampling:
    temperature: 1.1
    max_tokens: 100
    top_p: 0.95
    n: 1
    stop: ["\n"]
    logprobs: True
