run_name: native_mcts_small
split: "valid"
data_dir: datasets/small_dataset.jsonl
description: |
    This configuration is for testing the fast MCTS inference method on the log problem in small_Dataset
    The loop is Lean -> Fast PV -> Completion -> Repeat.
branching_factor: 1

mcts:
    num_procs: 1
    num_iters: 1
    max_actions: 1
    max_depth: 4

lean:
    num_procs: 1

fast_policy_value:
    num_procs: 1
    batch_size: 40
    model:
        model: "deepseek-ai/DeepSeek-Prover-V1.5-RL"
        max_num_batched_tokens: 8192
        trust_remote_code: True
    sampling:
        max_tokens: 200
        temperature: 1.0
        top_p: 0.95
        n: 1
        stop: ["/--", "```", "--"]
        logprobs: True

completion:
    num_procs: 1
    batch_size: 1

# policy_value_post_proces:
#     num_procs: 1