run_name: fast_linear_inference_valid
split: "valid"
data_dir: datasets/minif2f.jsonl

linear_inference:
    num_procs: 163
    num_comments: 1

completion:
    num_procs: 8
    batch_size: 40
    model:
        model: "deepseek-ai/DeepSeek-Prover-V1.5-RL"
        max_num_batched_tokens: 8192
        trust_remote_code: True
    sampling:
        max_tokens: 1024
        temperature: 0.0
        top_k: 1
        top_p: 1.0
        stop: ["\n", "```"]

lean:
    num_procs: 24