run_name: medium_valid
split: ["valid"]
data_dir: datasets/minif2f.jsonl
description: |
    This configuration is for running the fast MCTS inference method on the full minif2f dataset.
    The loop is Lean -> Completion -> Repeat.
    Value-less agent.

mcts:
    num_procs: 61
    agent_class: "LazyLeanAgent"
    agent_kwargs:
        request_formula: "sqrt"
        max_num_completions: 10
        valueless: True
    search_kwargs:
        num_iters: 500
        num_crawlers: 5
        search_time_limit: 3600
    tree_kwargs:
        c: 1

completion:
    num_procs: 8
    batch_size: 40
    timeout: 30
    model:
        model: "deepseek-ai/DeepSeek-Prover-V1.5-RL"
        max_num_batched_tokens: 8192
        trust_remote_code: True
    sampling:
        max_tokens: 256
        temperature: 1.0
        top_p: .95
        stop: ["/--", "```"]
        logprobs: 0

lean:
    num_procs: 128
