run_name: fast_mcts_debug
split: "valid"
data_dir: datasets/minif2f.jsonl
description: |
    This configuration is for debugging the fast MCTS inference method on the validation set.
    The loop is Lean -> Completion -> Repeat.
    Value-less agent.

mcts:
    num_procs: 1
    agent_class: "LazyLeanAgent"
    agent_kwargs:
        request_formula: "conservative"
        max_num_completions: 5
        valueless: True
    search_kwargs:
        num_iters: 20
        num_crawlers: 2
        search_time_limit: 3600.0

completion:
    num_procs: 1
    batch_size: 5
    timeout: 30
    model:
        model: "deepseek-ai/DeepSeek-Prover-V1.5-RL"
        max_num_batched_tokens: 8192
        trust_remote_code: True
    sampling:
        max_tokens: 256
        temperature: 2.0
        top_p: 1.0
        stop: ["\n", "```"]
        logprobs: 0

lean:
    num_procs: 1
