run_name: mcts_inference_valid
data_dir: /home/ubuntu/ohm-tree-IL/plasma-converter/datasets/minif2f.jsonl
split: 'valid'

worker:
  num_procs: 163

context:
  num_procs: 3
  batch_size: 40

lean:
  num_procs: 24

policy_value:
  num_procs: 5
  batch_size: 40
  sampling:
    max_tokens: 512
    temperature: 0.0
    top_k: 1
    top_p: 1.0
    stop: ["\n", "```"]
