run_name: linear_inference_debug
split: "valid"
data_dir: datasets/quickstart_problem.jsonl
decription: |
    This configuration is for debugging the linear inference method on the validation set.
    The loop is Lean -> Context -> Policy Value -> Completion -> Repeat.

linear_inference_debug:
    num_procs: 1
    max_depth: 4

completion:
    num_procs: 0
    batch_size: 40
    model:
        model: "deepseek-ai/DeepSeek-Prover-V1.5-RL"
        max_num_batched_tokens: 8192
        trust_remote_code: True
    sampling:
        max_tokens: 1024
        temperature: 0.0
        top_k: 1
        top_p: 1.0
        stop: ["\n", "```"]


lean:
    num_procs: 1

fast_policy_value:
    num_procs: 1
    batch_size: 40
    num_comments: 2
    model:
        model: "deepseek-ai/DeepSeek-Prover-V1.5-RL"
        max_num_batched_tokens: 8192
        trust_remote_code: True
    sampling:
        max_tokens: 200
        temperature: 1.0
        top_p: 0.95
        n: 2
        stop: ["/--", "```"]
        logprobs: True

context:
    num_procs: 0
    batch_size: 40
    model:
        model: "deepseek-ai/DeepSeek-Prover-V1.5-RL"
        max_num_batched_tokens: 8192
        trust_remote_code: True
    sampling:
        max_tokens: 1024
        temperature: 0.0
        top_k: 1
        top_p: 1.0
        
