run_name: linear_inference_debug
split: "valid"
data_dir: datasets/minif2f.jsonl
description: |
    This configuration is for running the linear inference method on the validation set.
    The loop is Lean -> Completion -> Repeat.

game_class: "scratchpad"

linear:
    num_procs: 1
    num_comments: 1

completion:
    chat: True
    num_procs: 1
    batch_size: 40
    timeout: 30
    model:
        model: "deepseek-ai/DeepSeek-Prover-V1.5-RL"
        max_num_batched_tokens: 8192
        trust_remote_code: True
    sampling:
        max_tokens: 1024
        temperature: 0.0
        top_k: 1
        top_p: 1.0
        stop: ["\n", "```"]
        logprobs: 0

lean:
    num_procs: 1