run_name: one-step-quickstart
split: "valid"
data_dir: datasets/minif2f.jsonl
description: |
    This configuration is for debugging the fast MCTS inference method on the validation set.
    The loop is Lean -> Fast PV -> Completion -> Repeat.

linear_inference_debug:
    num_procs: 122
    max_depth: 6

lean:
    num_procs: 22

fast_policy_value:
    num_procs: 8
    batch_size: 80
    num_comments: 10
    model:
        model: "deepseek-ai/DeepSeek-Prover-V1.5-RL"
        max_num_batched_tokens: 8192
        trust_remote_code: True
    sampling:
        max_tokens: 200
        temperature: 1.0
        top_p: 0.95
        n: 10
        stop: ["/--", "```"]
        logprobs: True

context:
    num_procs: 0

completion:
    num_procs: 0