run_name: debug_mcts_native
split: ["valid", "test"]
data_dir: datasets/small_dataset.jsonl
description: |
    This configuration is for running the fast MCTS inference method on the full minif2f dataset.
    The loop is Lean -> Completion -> Repeat.
    Value-less agent.

mcts:
    num_procs: 6
    max_num_completions: 2
    search_kwargs:
        num_iters: 10

completion:
    num_procs: 6
    batch_size: 40
    timeout: 30
    model:
        model: "deepseek-ai/DeepSeek-Prover-V1.5-RL"
        max_num_batched_tokens: 8192
        trust_remote_code: True
    sampling:
        max_tokens: 200
        temperature: 1.0
        top_p: 0.95
        n: 2
        stop: ["/--", "```"]
        logprobs: True

lean:
    num_procs: 6
