run_name: minif2f-valid-one-step
split: "valid"
data_dir: datasets/minif2f.jsonl
description: |
    This configuration is for debugging the fast MCTS inference method on the validation set.
    The loop is Lean -> Fast PV -> Completion -> Repeat.

mcts:
    num_procs: 122
    num_iters: 100
    max_actions: 10
    max_depth: 20

lean:
    num_procs: 30

fast_policy_value:
    num_procs: 8
    batch_size: 80
    num_comments: 10
    model:
        model: "deepseek-ai/DeepSeek-Prover-V1.5-RL"
        max_num_batched_tokens: 8192
        trust_remote_code: True
    sampling:
        max_tokens: 200
        temperature: 1.0
        top_p: 0.95
        n: 10
        stop: ["/--", "```"]
        logprobs: True

context:
    num_procs: 0

completion:
    num_procs: 0