run_name: one-step-valid
split: "valid"
data_dir: datasets/quickstart_problem.jsonl
description: |
    This configuration is for debugging the fast MCTS inference method on the validation set.
    The loop is Lean -> Fast PV -> Completion -> Repeat.

mcts:
    num_procs: 1
    num_iters: 1
    max_actions: 2

completion:
    num_procs: 0

lean:
    num_procs: 24

fast_policy_value:
    num_procs: 8
    batch_size: 40
    num_comments: 2
    model:
        model: "deepseek-ai/DeepSeek-Prover-V1.5-RL"
        max_num_batched_tokens: 8192
        trust_remote_code: True
    sampling:
        max_tokens: 200
        temperature: 1.0
        top_p: 0.95
        n: 2
        stop: ["/--", "```"]
        logprobs: True